analyzer:
  errors:
    missing_return: error

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - android/**
    - build/**
    - ios/**
    - lib/generated/**
    - test/**
